// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/cec/[[...section]]" | "/chat" | "/clubs/[slug]" | "/clubs/[slug]/[view]" | "/clubs/[slug]/events" | "/clubs/[slug]/money" | "/clubs/[slug]/people" | "/clubs/[slug]/settings" | "/clubs/[slug]/workspace" | "/discover" | "/embed/[slug]" | "/join" | "/join/cec" | "/start" | "/you"
type AppRouteHandlerRoutes = "/api/cec/[...path]"
type PageRoutes = never
type LayoutRoutes = "/" | "/embed"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/cec/[...path]": { "path": string[]; }
  "/cec/[[...section]]": { "section"?: string[]; }
  "/chat": {}
  "/clubs/[slug]": { "slug": string; }
  "/clubs/[slug]/[view]": { "slug": string; "view": string; }
  "/clubs/[slug]/events": { "slug": string; }
  "/clubs/[slug]/money": { "slug": string; }
  "/clubs/[slug]/people": { "slug": string; }
  "/clubs/[slug]/settings": { "slug": string; }
  "/clubs/[slug]/workspace": { "slug": string; }
  "/discover": {}
  "/embed": {}
  "/embed/[slug]": { "slug": string; }
  "/join": {}
  "/join/cec": {}
  "/start": {}
  "/you": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/embed": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
