import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
const dir=mkdtempSync(join(tmpdir(),'cec-mail-'));
Object.assign(process.env,{CEC_DATABASE:join(dir,'cec.sqlite'),CEC_EMAIL_MODE:'capture',CEC_EMAIL_KEY:randomBytes(32).toString('hex'),CEC_EMAIL_FROM:'Club OS <test@example.test>',CEC_ORIGIN:'http://localhost:3120'});
const {db,tx,password,session,user}=await import('../lib/cec/db.ts');
const {emailAction,emailState,requestReset,consumeEmailToken,queueTaskEmail}=await import('../lib/cec/email.ts');
const {deliverOnce}=await import('../scripts/email-worker.mjs');
const {invites}=await import('../lib/cec/invites.ts');
const d=db();
const captureToken=id=>JSON.parse(readFileSync(join(dir,'mail',id+'.json'),'utf8')).text.match(/token=([a-f0-9]+)/)[1];
try {
  for(const [id,role] of [['officer','officer'],['member','member']]) d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run(id,id,id+'@example.test',password('old-password-test'),role,'',0);
  const officer={id:'officer',email:'officer@example.test',role:'officer'},member={id:'member',email:'member@example.test',role:'member'};
  assert.equal(d.prepare('SELECT MAX(version) n FROM schema_migrations').get().n,3);
  assert.equal(d.prepare('PRAGMA foreign_key_check').all().length,0);
  emailAction(member,'verify/request',{});const queued=d.prepare('SELECT * FROM email_jobs').get();
  assert(!queued.payload.includes('example.test'));assert(!queued.payload.includes('token='));
  assert.equal((await deliverOnce()).status,'captured');const token=captureToken(queued.id);
  assert.notEqual(d.prepare('SELECT hash FROM email_tokens').get().hash,token);
  assert.throws(()=>consumeEmailToken('reset',{token,password:'new-password-test'}),/invalid or expired/);
  consumeEmailToken('verify',{token});assert(emailState(member).verified);
  assert.throws(()=>consumeEmailToken('verify',{token}),/invalid or expired/);
  assert(!JSON.stringify(emailState(member)).includes(token));
  const existing=session('member');assert.deepEqual(requestReset({email:member.email}),requestReset({email:'missing@example.test'}));
  assert.equal((await deliverOnce()).status,'captured');const reset=d.prepare("SELECT * FROM email_jobs WHERE kind='reset'").get();const resetToken=captureToken(reset.id);
  consumeEmailToken('reset',{token:resetToken,password:'new-password-test'});assert.equal(user(existing),null);
  assert.equal(d.prepare("SELECT role FROM users WHERE id='member'").get().role,'member');
  assert.throws(()=>consumeEmailToken('reset',{token:resetToken,password:'again-password-test'}),/invalid or expired/);
  const task={id:'task1',version:1,data:{assignee:'member',status:'assigned'}};
  d.prepare('INSERT INTO items(id,kind,owner,data,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?)').run(task.id,'task','officer',JSON.stringify(task.data),new Date().toISOString(),new Date().toISOString(),1);
  const before=d.prepare('SELECT COUNT(*) n FROM email_jobs').get().n;
  assert.throws(()=>tx(()=>{queueTaskEmail(task,'assignment');throw Error('rollback');}),/rollback/);
  assert.equal(d.prepare('SELECT COUNT(*) n FROM email_jobs').get().n,before);
  tx(()=>queueTaskEmail(task,'assignment'));tx(()=>queueTaskEmail(task,'assignment'));
  assert.equal(d.prepare("SELECT COUNT(*) n FROM email_jobs WHERE kind='assignment'").get().n,1);
  emailAction(member,'preferences',{taskNotifications:false});assert.equal((await deliverOnce()).status,'cancelled');emailAction(member,'preferences',{taskNotifications:true});
  const invite=invites(officer,'create',{label:'test',days:7,max_uses:2,email_domain:'example.test'});
  assert.throws(()=>emailAction(member,'invite',{code:invite.code,email:member.email}),/officer/i);
  emailAction(officer,'invite',{code:invite.code,email:member.email});invites(officer,'revoke',{code:invite.code});assert.equal((await deliverOnce()).status,'cancelled');
  task.version=2;tx(()=>queueTaskEmail(task,'assignment'));
  d.prepare("UPDATE memberships SET status='left' WHERE user_id='member'").run();assert.equal((await deliverOnce()).status,'cancelled');d.prepare("UPDATE memberships SET status='active' WHERE user_id='member'").run();
  Object.assign(process.env,{CEC_EMAIL_MODE:'resend',CEC_ORIGIN:'https://club.example.test',RESEND_API_KEY:'synthetic'});
  task.version=3;tx(()=>queueTaskEmail(task,'assignment'));const attempts=[],now=Date.now();
  const send=async(url,options)=>{attempts.push(options);return attempts.length===1?new Response('{}',{status:503}):Response.json({id:'receipt'});};
  assert.equal((await deliverOnce({send,now})).status,'queued');assert.equal((await deliverOnce({send,now:now+31000})).status,'accepted');
  assert.equal(attempts[0].headers['Idempotency-Key'],attempts[1].headers['Idempotency-Key']);assert.equal(attempts[0].body,attempts[1].body);
  task.version=4;tx(()=>queueTaskEmail(task,'assignment'));const stranded=d.prepare("SELECT id FROM email_jobs WHERE status='queued'").get().id;
  d.prepare("UPDATE email_jobs SET status='processing',lease_until=?,first_attempt=?,attempts=1 WHERE id=?").run(now-1,now-24*3600000,stranded);
  assert.equal((await deliverOnce({send,now})).status,'failed');assert.equal(attempts.length,2);
  task.version=5;tx(()=>queueTaskEmail(task,'assignment'));assert.equal((await deliverOnce({env:{...process.env,CEC_EMAIL_MODE:'capture'}})).status,'cancelled');
  task.version=6;tx(()=>queueTaskEmail(task,'revision'));
  const leased=d.prepare("SELECT id FROM email_jobs WHERE status='queued'").get().id;
  d.prepare("UPDATE email_jobs SET status='processing',lease_until=?,first_attempt=?,attempts=1 WHERE id=?").run(now+60000,now,leased);
  assert.equal((await deliverOnce({send,now:now+1000})).status,'idle');
  assert.equal((await deliverOnce({send,now:now+61000})).status,'accepted');
  task.version=7;tx(()=>queueTaskEmail(task,'revision'));
  assert.equal((await deliverOnce({send:async()=>new Response('{}',{status:401})})).status,'failed');
  // Expiration is enforced at token consumption, independently of delivery status.
  process.env.CEC_EMAIL_MODE='capture';process.env.CEC_ORIGIN='http://localhost:3120';
  emailAction(member,'verify/request',{});assert.equal((await deliverOnce()).status,'captured');
  const expiring=d.prepare("SELECT id,token_hash FROM email_jobs WHERE kind='verify' ORDER BY created DESC LIMIT 1").get();
  const expiredToken=captureToken(expiring.id);d.prepare('UPDATE email_tokens SET expires=0 WHERE hash=?').run(expiring.token_hash);
  assert.throws(()=>consumeEmailToken('verify',{token:expiredToken}),/invalid or expired/);
  process.env.CEC_EMAIL_MODE='disabled';assert.throws(()=>requestReset({email:member.email}),/not configured/);assert.equal((await deliverOnce()).status,'disabled');
  console.log('Email tests passed: encrypted queue, one-use verification/reset, session revocation, atomic rollback, preferences, access checks, retries/idempotency, expiry and mode isolation.');
} finally {d.close();rmSync(dir,{recursive:true,force:true});}
