import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
const dir=mkdtempSync(join(tmpdir(),'cec-tools-'));process.env.CEC_DATABASE=join(dir,'cec.sqlite');process.env.CEC_EMAIL_MODE='disabled';process.env.CEC_ALLOW_EPHEMERAL='1';
const {db,password,tx,item,items}=await import('../lib/cec/db.ts');
const {mutate}=await import('../lib/cec/service.ts');
const {toolsState,toolsAction,importPreview,clubCalendar}=await import('../lib/cec/officer-tools.ts');
const {parseCSV}=await import('../lib/cec/csv.ts');
const d=db();const u={id:'o',name:'Officer',email:'o@example.test',role:'officer'},receiver={id:'r',name:'Receiver',email:'r@example.test',role:'officer'},m={id:'m',name:'Member',email:'m@example.test',role:'member'};
try{
 for(const p of [u,receiver,m])(await d.prepare('INSERT INTO users VALUES(?,?,?,?,?,?,?)').run(p.id,p.name,p.email,password('synthetic-password'),p.role,'',0));
 assert.deepEqual(parseCSV('\uFEFFname,notes\r\n"A, B","line 1\nline 2"').rows,[['A, B','line 1\nline 2']]);
 assert.throws(()=>parseCSV('a,b\n"bad,b'),/Unclosed/);assert.throws(()=>parseCSV('a,a\nb,c'),/unique/);
 assert.throws(()=>parseCSV('a\n'+Array(101).fill('b').join('\n')),/100 rows/);
 (await assert.rejects(async ()=>(await toolsState(m)),/officer/i));(await assert.rejects(async ()=>(await toolsAction(m,'calendar/enable',{})),/officer/i));
 let b={kind:'contacts',csv:'name,organization,email,notes\n"Amy, Chen",Sponsor Inc,amy@example.test,=literal\nBob,Sponsor Two,bob@example.test,Notes'};
 let p=(await importPreview(u,b));assert.equal(p.added,2);assert.equal((await items('contact')).length,0);
 let result=(await toolsAction(u,'import/commit',{...b,revision:p.revision}));assert.equal(result.added,2);assert.equal((await items('contact')).length,2);
 assert.equal((await toolsAction(u,'import/commit',{...b,revision:p.revision})).replayed,true);assert.equal((await items('contact')).length,2);
 assert.equal((await items('contact')).find(r=>r.data.email==='amy@example.test').data.notes,'=literal');
 b={kind:'contacts',csv:'name,organization,email\nNew,Sponsor,new@example.test\nInvalid,Sponsor,bad'};p=(await importPreview(u,b));assert.equal(p.errors,1);(await assert.rejects(async ()=>(await toolsAction(u,'import/commit',{...b,revision:p.revision})),/invalid rows/));assert.equal((await items('contact')).length,2);
 b={kind:'roster',csv:'Full Name,Email\nNew Member,new@example.test',mapping:{name:'Full Name'}};p=(await importPreview(u,b));(await toolsAction(u,'import/commit',{...b,revision:p.revision}));assert.equal((await d.prepare("SELECT COUNT(*) n FROM roster_prospects").get()).n,1);assert.equal((await d.prepare("SELECT COUNT(*) n FROM users").get()).n,3);
 b={kind:'contacts',csv:'name,organization,email\nConcurrent,Org,concurrent@example.test'};p=(await importPreview(u,b));
 const competing={...b,csv:b.csv+'\n'};const other=(await importPreview(receiver,competing));(await toolsAction(receiver,'import/commit',{...competing,revision:other.revision}));
 (await assert.rejects(async ()=>(await toolsAction(u,'import/commit',{...b,revision:p.revision})),/changed/));
 const meeting=(await mutate(u,'create',{kind:'meeting',data:{title:'Planning',starts_at:'2026-01-01T12:00:00Z',agenda:'Discuss launch',decision:''}})).id;
 const work={meeting_id:meeting,version:1,request_id:'once',decision:'Launch a pilot',tasks:[{title:'Pilot checklist',assignee:'m',due_at:'2026-01-02T12:00:00Z'}]};
 const follow=(await toolsAction(u,'meeting/commit',work));assert.equal(follow.tasks.length,1);assert.equal((await item(follow.tasks[0])).data.origin,'Meeting: Planning');
 assert.deepEqual((await toolsAction(u,'meeting/commit',work)),follow);assert.equal((await items('task')).length,1);
 (await assert.rejects(async ()=>(await toolsAction(u,'meeting/commit',{...work,decision:'Different'})),/different follow-ups/));
 (await assert.rejects(async ()=>(await toolsAction(u,'meeting/commit',{...work,request_id:'new'})),/Meeting changed/));
 const previous=(await item(meeting));(await assert.rejects(async ()=>(await toolsAction(u,'meeting/commit',{...work,version:previous.version,request_id:'invalid',tasks:[{title:'Invalid',assignee:'missing',due_at:'2026-01-02T12:00:00Z'}]})),/Select a member/));assert.equal((await item(meeting)).version,previous.version);
 (await assert.rejects(async ()=>(await tx(async ()=>{(await mutate(u,'create',{kind:'contact',data:{title:'Rollback',organization:'Rollback',relationship:'Sponsor'}}));throw Error('rollback');})),/rollback/));assert.equal((await items('contact')).length,3);
 const event=(await mutate(u,'create',{kind:'event',data:{title:'Public event',description:'Public description',location:'Room A',starts_at:'2026-01-01T12:00:00Z',ends_at:'2026-01-01T13:00:00Z',capacity:10,status:'published'}})).id;
 (await d.prepare('INSERT INTO rsvps(event_id,user_id,status,created_at) VALUES(?,?,?,?)').run(event,'m','confirmed',new Date().toISOString()));
 b={kind:'attendance',event_id:event,csv:'email,attendance\nm@example.test,present'};p=(await importPreview(u,b));(await toolsAction(u,'import/commit',{...b,revision:p.revision}));assert.equal((await d.prepare('SELECT attendance FROM rsvps WHERE event_id=?').get(event)).attendance,'present');
 const key=(await toolsAction(u,'calendar/enable',{})).token;let feed=(await clubCalendar(key));assert(feed.includes('UID:'+event));assert(feed.includes('LOCATION:Room A'));
 let ev=(await item(event));(await mutate(u,'update',{id:event,version:ev.version,data:{...ev.data,location:'Room B'}}));feed=(await clubCalendar(key));assert(feed.includes('LOCATION:Room B'));assert(feed.includes('SEQUENCE:2'));
 ev=(await item(event));(await mutate(u,'update',{id:event,version:ev.version,data:{...ev.data,status:'draft',title:'Private draft',description:'Secret draft'}}));feed=(await clubCalendar(key));assert(feed.includes('STATUS:CANCELLED'));assert(!feed.includes('Private draft'));assert(!feed.includes('Secret draft'));
 (await toolsAction(u,'calendar/disable',{}));(await assert.rejects(async ()=>(await clubCalendar(key)),/unavailable/));
 const packet=(await toolsAction(u,'handoff/create',{recipient_id:'r',title:'Fall handoff',notes:'Review access'})).id;
 (await assert.rejects(async ()=>(await toolsAction(u,'handoff/check',{id:packet,version:1,index:0,done:true})),/receiving officer/));
 (await assert.rejects(async ()=>(await toolsAction(receiver,'handoff/accept',{id:packet,version:1})),/Complete the checklist/));
 for(let i=0;i<4;i++)(await toolsAction(receiver,'handoff/check',{id:packet,version:i+1,index:i,done:true}));
 (await toolsAction(receiver,'handoff/accept',{id:packet,version:5}));assert((await toolsState(u)).packets[0].accepted_at);
 assert.equal((await toolsState(u)).overdue.length,1);assert.equal((await d.prepare('PRAGMA foreign_key_check').all()).length,0);
 console.log('Officer tools PASS: CSV parsing, mapping, atomic imports, replay, prospects, attendance, meeting provenance/versioning, nested rollback, dashboard, handoff access and calendar updates/cancellation.');
}finally{d.close();rmSync(dir,{recursive:true,force:true});}
